### ISSUE TITLE
The Requested Service Type is not Available For This Account Error

### ISSUE THREAD

**Issue by andymok221** [brewski/ontrac-web-services#2]
When I run the sample on the readme page, I get `The Requested Service Type is not Available For This Account Error`. What does it mean? Is the error account specific?

**Comment by brewski** [comment]
Can you provide a backtrace?

**Comment by brewski** [comment]
I'm seeing the same errors now in our development environment. We are running in production just fine with this gem, so I suspect something is awry with their sandbox environment.

I have updated the gem to improve the error handing and updated the README.md file accordingly. The `Ontrac::WebServices::ServiceException` exception now has `#root_error` and `#sub_errors` methods that will provide more details as to what went wrong when an error occurs. The updated example uses these methods to provide more details. I haven't pushed the updated gem to rubygems yet, so if you want to try it out you'll need to update your Gemfile to point to https://github.com/brewski/ontrac-web-services

**Comment by andymok221** [comment]
It is back to normal. Thanks.
